# Get git version
execute_process(
    COMMAND git describe --tags --always --dirty
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE UFIFO_GIT_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(UFIFO_GIT_VERSION MATCHES "^v?([0-9]+)\\.([0-9]+)\\.([0-9]+)")
    set(UFIFO_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(UFIFO_VERSION_MINOR ${CMAKE_MATCH_2})
    set(UFIFO_VERSION_PATCH ${CMAKE_MATCH_3})
else()
    set(UFIFO_GIT_VERSION "v0.0.1")
    set(UFIFO_VERSION_MAJOR 0)
    set(UFIFO_VERSION_MINOR 0)
    set(UFIFO_VERSION_PATCH 1)
endif()
add_compile_definitions(UFIFO_VERSION="${UFIFO_GIT_VERSION}")

# print version
message(STATUS "UFIFO_VERSION: ${UFIFO_GIT_VERSION}")
message(STATUS "UFIFO_VERSION_MAJOR: ${UFIFO_VERSION_MAJOR}")
message(STATUS "UFIFO_VERSION_MINOR: ${UFIFO_VERSION_MINOR}")
message(STATUS "UFIFO_VERSION_PATCH: ${UFIFO_VERSION_PATCH}")
